# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
