# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0002_auto_20171223_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
