# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-23 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0003_message_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
